# Grammar for parsing date, time and timestamps.
# Source: https://github.com/xored/peg/blob/master/docs/grammar-examples.md

Timestamp <- DateTime / FreeDateTime

# Times
Hour <- [0-1] [0-9] / '2' [0-4]
Minute <- [0-5] [0-9]
Second <- [0-5] [0-9] / '60'
Fraction <- ('.' / ',') [0-9]+
IsoTz <- 'Z' / ('+' / '-') Hour (':'? Minute)?
TzLetter <- [A-Z]
TzAbbr <- TzLetter TzLetter (TzLetter (TzLetter TzLetter?)?)?
Tz <- IsoTz / TzAbbr
Hm <- Hour ':' Minute Fraction?
HmSec <- Hour ':' Minute ':' Second Fraction?
Time <- ('T' ' '?)? (HmSec / Hm) (' '? Tz)?

# Dates
Year <- [0-9] [0-9] [0-9] [0-9]
Month <- '0' [1-9] / '1' [0-2]
Day <- '0' [1-9] / [1-2] [0-9] / '3' [0-1]
Date <- Year '-' Month ('-' Day)?

# Combined
DateTime <- Date ' '? Time

# Free style
MonthAbbr <- 'Jan' / 'Feb' / 'Mar' / 'Apr' / 'May' / 'Jun' / 'Jul' / 'Aug' / 'Sep' / 'Sept' / 'Oct' / 'Nov' / 'Dec'
WeekDayAbbr <- 'Mon' / 'Tu' / 'Tue' / 'Tues' / 'Wed' / 'Th' / 'Thu' / 'Thur' / 'Thurs' / 'Fri' / 'Sat' / 'Sun'
FreeDateTime <- WeekDayAbbr ' ' MonthAbbr ' ' Day ' ' Time ' ' Year

