# PEG Test
#
# This is the flavor of PEG that `cl-peg-yapp` works with. 
# 
# It's also made to test the parser.
#
# Note that the following char classes are predefined in the
# parser for convenience: 
#
# unipoint
# numeric
# alpha
# alphanum
# string

Grammar    <- ComEndLine* (Definition ComEndLine*)+
ComEndLine <- ' '* ('# ' Comment)? EndLine

EndLine    <-   u000D         # CR
              / u000A         # LF
              / (u000D
                 u000A)



Spacing    <- ComEndLine? ' '+
Comment    <- (!EndLine alphanum)+

